### ISSUE TITLE
liste der Tätigkeiten

### ISSUE THREAD

**Issue by Pexem** [MeMo-KBC/bio-medRxiv#11]
- Liste der verschiedenen Tätigkeiten in "author contributions" erstellen.
- Aufteilung in Verben und damit zusammenhängenden Substantiven (bspw. "perfomed" & "experiments")

**Comment by phschaer** [comment]
Bitte prüfen, ob es hier schon fertige Schemata oder Taxonomien gibt, die sich mit dem Thema der Author-Contribution beschäftigen. Beispiel dafür kann das hier sein: https://www.elsevier.com/authors/policies-and-guidelines/credit-author-statement

Bei der großen Varianz in den Nennungen macht es wahrscheinlich Sinn, dass man auf diese Taxonomien abbildet, anstatt alle Feinheiten der Originalmeldungen zu übernehmen.
