### ISSUE TITLE
labelfunction name short/long [3]

### ISSUE THREAD

**Issue by LauraFredrich** [MeMo-KBC/bio-medRxiv#26]

**Comment by macmacpri** [comment]
First draft of a labeling function for name short/long.

On closer inspection, I notice that the labelling function "same_starting_letters(c):" is probably a throttler rather than a labelling function and fits into the issue "throttler für name short/long"

**Comment by macmacpri** [comment]
Two  labeling functions for name short/long.

Checking both for the vertical percentile of the Mentions
