### ISSUE TITLE
list synonymes "author contributions"

### ISSUE THREAD

**Issue by Pexem** [MeMo-KBC/bio-medRxiv#6]
- liste von verschiedenen Titeln für "author contribution" erstellen

**Comment by Wanille** [comment]
## Search for variations of a word recursively in subdirectories
use this command on the server. If you want to login use SSH on your PC. login with username and password. Username is the first letter of your name + your surname (Nils Grote --> ngrote) your password should be your username. If you already changed your username and can't remember tell me i'll reset it. To login to the server use SSH follow this [tutorial](https://www.howtogeek.com/311287/how-to-connect-to-an-ssh-server-from-windows-macos-or-linux/).
```
grep -inor --include \*.html "author contribution" | 
sort -t: -u -k1,3 > 
/home/MeMo-KBC/bio-medrxiv/found_variations.txt
```
- grep
	- i -> case insensitive
	- n -> number of line where word was found
	- o -> output only match
	- r -> recursively search
	- --include \*.html -> search in files ending with html
- sort
	- t: -> delimiter is ":"
	- u -> deduplicate
	- k1,3 -> sort by column 1 - 3
